#!/usr/bin/env python3
"""Generate Codex and Copilot/VS Code adapters from the Claude-canonical fleet.

The authored source remains ``agents/*.md`` and ``skills/**``. Other hosts do not share Claude's
agent frontmatter, plugin namespace, hook payload, or skill invocation syntax, so loading those
files unchanged creates plausible-looking but false controls. This generator makes those
differences explicit:

* Copilot/VS Code agents use native tool aliases. Agents protected by Claude's session-wide Bash
  hook receive no ``execute`` tool because neither host exposes the active agent identity on
  ``PreToolUse``.
* Codex agents use standalone TOML and request ``read-only`` or ``workspace-write`` sandbox mode
  from the canonical write-tool authority, while naming that parent permissions can override it.
* ``.claude/agents`` carries generated Markdown staging profiles for Codex's official ``/import``
  migration. They retain source-host tool metadata while sharing the adapted Codex instructions.
* Each host gets a skill copy with valid YAML, no Claude plugin namespace, and no direct
  plugin-root paths. Copilot retains its explicit-invocation frontmatter; Codex expresses the
  same rule through ``agents/openai.yaml``.

Generated directories are replaced as a unit by ``--write`` and checked byte-for-byte by the fleet
validator. Never edit generated output directly.
"""

from __future__ import annotations

import argparse
import importlib
import json
import os
import re
import shutil
import stat
import subprocess
import sys
from pathlib import Path
from types import ModuleType


COPILOT_AGENTS = Path(".github/agents")
CODEX_AGENTS = Path(".codex/agents")
CLAUDE_IMPORT_AGENTS = Path(".claude/agents")
COPILOT_SKILLS = Path("platforms/copilot/skills")
CODEX_PLUGIN_ROOT = Path("plugins/sde-agents")
CODEX_SKILLS = CODEX_PLUGIN_ROOT / "skills"
GENERATED_ROOTS = (
    COPILOT_AGENTS,
    CODEX_AGENTS,
    CLAUDE_IMPORT_AGENTS,
    COPILOT_SKILLS,
    CODEX_SKILLS,
)
RETIRED_GENERATED_ROOTS = (Path("platforms/portable"),)

GENERATED_MARKER = "Generated by scripts/generate_platform_adapters.py; do not edit."
CLAUDE_REFERENCE = Path(
    "prompt-craft/references/claude-code-frontmatter.md"
)

COPILOT_TOOL_ORDER = ("read", "search", "edit", "execute", "web", "agent")
COPILOT_TOOL_MAP = {
    "Read": "read",
    "Grep": "search",
    "Glob": "search",
    "Write": "edit",
    "Edit": "edit",
    "NotebookEdit": "edit",
    "Bash": "execute",
    "WebFetch": "web",
    "WebSearch": "web",
    "Agent": "agent",
}

IDENTITY_FIELDS = (
    "name",
    "version",
    "description",
    "author",
    "homepage",
    "repository",
    "license",
    "keywords",
)
COPILOT_COMPONENTS = {
    "agents": "./.github/agents/",
    "skills": "./platforms/copilot/skills/",
    "hooks": "./hooks/copilot-hooks.json",
}
CODEX_COMPONENTS = {
    "skills": "./skills/",
}

_FLEET_TOKEN_RE = re.compile(r"sde-agents:(?P<name>[a-z0-9]+(?:-[a-z0-9]+)*)")
_SLASH_FLEET_TOKEN_RE = re.compile(
    r"/sde-agents:(?P<name>[a-z0-9]+(?:-[a-z0-9]+)*)"
)
_CLAUDE_SKILL_PATH_RE = re.compile(
    r"`?\$\{CLAUDE_PLUGIN_ROOT\}/skills/"
    r"(?P<name>[a-z0-9]+(?:-[a-z0-9]+)*)"
    r"(?:/(?P<resource>[A-Za-z0-9_./<>*-]+))?`?"
)
_CLAUDE_AGENT_PATH_RE = re.compile(
    r"`?\$\{CLAUDE_PLUGIN_ROOT\}/agents/"
    r"(?P<name>[a-z0-9]+(?:-[a-z0-9]+)*)\.md`?"
)
_CLAUDE_SCRIPT_PATH_RE = re.compile(
    r"`?\$\{CLAUDE_PLUGIN_ROOT\}/scripts/"
    r"(?P<name>[A-Za-z0-9_-]+\.py)`?"
)
_CANONICAL_SKILL_PATH_RE = re.compile(
    r"`skills/(?P<name>[a-z0-9]+(?:-[a-z0-9]+)*)/"
    r"(?P<resource>[A-Za-z0-9_./<>*-]+)`"
)
_TEXT_RESOURCE_SUFFIXES = {".json", ".md", ".py", ".toml", ".yaml", ".yml"}
_FRONTMATTER_LINE_RE = re.compile(r"^(?P<key>[A-Za-z][A-Za-z0-9_-]*):")


def _validator_module() -> ModuleType:
    """Import the source grammar without making this script depend on its invocation path."""

    try:
        return importlib.import_module("scripts.validate_fleet")
    except ModuleNotFoundError:
        return importlib.import_module("validate_fleet")


def _definition_parts(path: Path) -> tuple[dict[str, str], str, list[str]]:
    """Return parsed fields, body, and raw frontmatter lines for one definition."""

    validator = _validator_module()
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    end = validator.frontmatter_span(lines)
    fields = None if end is None else validator.parse_frontmatter_lines(lines, end)
    if fields is None or end is None:
        raise ValueError(f"{path}: missing or malformed frontmatter")
    missing = sorted({"name", "description"} - fields.keys())
    if missing:
        raise ValueError(
            f"{path}: missing required frontmatter field(s): {', '.join(missing)}"
        )

    body = "\n".join(lines[end + 1 :]).lstrip("\n")
    if text.endswith("\n"):
        body += "\n"
    return fields, body, lines[1:end]


def _installed_skill(match: re.Match[str]) -> str:
    name = match.group("name")
    resource = match.group("resource")
    if not resource or resource == "SKILL.md":
        return f"the installed `{name}` skill"
    return f"the installed `{name}` skill's `{resource}` resource"


def _installed_agent(match: re.Match[str]) -> str:
    return f"the installed `{match.group('name')}` agent definition"


def _trusted_fleet_control(match: re.Match[str]) -> str:
    return (
        "an operator-provided trusted copy of the fleet's "
        f"`{match.group('name')}` control"
    )


def adapt_text(text: str, host: str) -> str:
    """Rewrite only runtime references; preserve prose and platform-specific source guidance."""

    if host not in {"codex", "copilot", "portable"}:
        raise ValueError(f"unknown adapter host {host!r}")

    text = text.replace(
        "`${CLAUDE_PLUGIN_ROOT}/skills/<name>/SKILL.md`",
        "the installed skill named by this step",
    )
    text = text.replace(
        "`${CLAUDE_PLUGIN_ROOT}/agents/<name>.md`",
        "the installed agent definition for the selected role",
    )
    text = _CLAUDE_SKILL_PATH_RE.sub(_installed_skill, text)
    text = _CLAUDE_AGENT_PATH_RE.sub(_installed_agent, text)
    # Claude expands plugin-root paths at runtime. Copilot/VS Code adapters and the nested Codex
    # plugin do not package this repository's control scripts, so retaining the path would point at
    # a file that does not exist while reading like an enforced boundary. Portable copies instead
    # require an operator-provided trusted control outside the target repository.
    text = _CLAUDE_SCRIPT_PATH_RE.sub(_trusted_fleet_control, text)
    text = _CANONICAL_SKILL_PATH_RE.sub(_installed_skill, text)

    # This sentence is an operational lookup, not Claude-format documentation. A project-scoped
    # skill may live in a different directory on every target host.
    text = text.replace(
        "the target repo's own `.claude/skills/service-onboard/SKILL.md` if it has one",
        "the target repo's own project-scoped `service-onboard` skill if this host discovers one",
    )
    text = text.replace(
        "(this plugin's copy — the variable is substituted with an absolute path)",
        "(this plugin's copy)",
    )
    text = re.sub(
        r"once the plugin is installed \(that variable is substituted for you with an absolute "
        r"path\)",
        "from the installed plugin",
        text,
    )
    text = text.replace(
        "(`CLAUDE.md`, which Claude Code loads for you; or an `AGENTS.md` it imports via "
        "`@AGENTS.md`)",
        "(`AGENTS.md`, `CLAUDE.md`, or the current host's project-instruction equivalent)",
    )
    text = re.sub(
        r"Record it in `CLAUDE\.md` \(what Claude Code loads and passes to builders\) — or, "
        r"if the repo keeps a portable `AGENTS\.md`, in a root `CLAUDE\.md` that "
        r"`@AGENTS\.md`-imports it;",
        "Record it in the repository's existing project-instruction file; prefer a portable "
        "`AGENTS.md`, and use `CLAUDE.md` when that is the repository's established convention;",
        text,
    )
    text = text.replace(
        "the target repo's CLAUDE.md at Phase 0",
        "the target repo's active project-instruction file at Phase 0",
    )
    text = text.replace(
        "path (usually the repo's CLAUDE.md)",
        "path to the repo's active project-instruction file",
    )
    text = re.sub(
        r"project context \(CLAUDE\.md, or an AGENTS\.md bridged by a CLAUDE\.md containing "
        r"`@AGENTS\.md` — see the\s+plugin README's \"Project context convention\"\)",
        "project context (prefer its existing `AGENTS.md`; otherwise use the instruction file "
        "that its host already loads — see the plugin README's \"Project context convention\")",
        text,
    )
    text = text.replace(
        "the preloaded craft skills' rules",
        "the required craft skills' rules",
    )
    text = text.replace(
        "which is **not** preloaded",
        "which is **not** in that required craft set",
    )
    text = text.replace(
        "its preloaded skills, and your prompt",
        "the skills supplied to it, and your prompt",
    )
    text = text.replace(
        "its preloaded skills, and the prompt",
        "the skills supplied to it, and the prompt",
    )
    text = text.replace(
        "Use the Agent tool to spawn",
        "Use the host's subagent mechanism to spawn",
    )
    text = text.replace(
        "via the Agent tool",
        "via the host's subagent mechanism",
    )
    text = text.replace(
        "If the Agent tool is unavailable",
        "If subagent spawning is unavailable",
    )
    text = re.sub(
        r"- \*\*Workers never see the parent conversation\.\*\* A spawned worker gets its "
        r"definition, the project context, the skills supplied to it, and your prompt — nothing "
        r"else unless you explicitly fork, resume, or supply it\. Construct exactly the context "
        r"each one needs; underspecified handoffs are the #1 multi-agent bug\.",
        "- **Never rely on implicit context inheritance.** A spawned worker receives only what the "
        "host's selected context or fork mode supplies. Choose that mode explicitly when "
        "available, and construct exactly the prompt and context the worker needs; underspecified "
        "handoffs are the #1 multi-agent bug.",
        text,
    )
    text = text.replace(
        "A spawned agent receives its definition, the project context, the skills supplied to it, "
        "and the prompt\nyou wrote — **not** the parent's conversation. Everything the worker "
        "needs must be in that prompt:",
        "A spawned agent receives only what the current host's context or fork mode supplies. "
        "Treat inheritance as absent unless you selected it explicitly, and put everything the "
        "worker needs in the prompt:",
    )
    text = text.replace(
        "authoring suites of Claude Code agents, skills, and workflows",
        "authoring suites of host-native agents, skills, and workflows",
    )
    text = text.replace(
        "from Claude Code subagent suites to production LLM orchestration",
        "from host-native subagent suites to production LLM orchestration",
    )
    text = text.replace(
        "A container, VM, or Claude Code sandbox counts only when those controls are actually",
        "A container, VM, or the current host's sandbox counts only when those controls are "
        "actually",
    )
    text = text.replace(
        "which preloads this skill",
        "which requires this skill",
    )
    text = text.replace(
        "The builder preloads both craft skills — do not name a skill, hand it a path, or tell it "
        "to load anything.",
        "The builder requires both craft skills — include that requirement in the spawn contract "
        "and ensure the host loads them before work.",
    )
    text = text.replace(
        "Claude Code's Workflow tool or equivalent",
        "the current host's workflow or orchestration mechanism",
    )
    text = text.replace(
        "A researcher with WebFetch and no\n  credentials",
        "A researcher with web access and no\n  credentials",
    )
    text = text.replace(
        "The craft skills for both layers — `backend-craft` and `frontend-craft` — are already in "
        "your\ncontext; you do not need to load them and there is nothing to resolve.",
        "The craft skills for both layers — `backend-craft` and `frontend-craft` — are required "
        "context for this role; load both installed skills before coding.",
    )
    text = text.replace(
        "`code-craft`, also already in your context:",
        "`code-craft`, also required context for this role:",
    )
    text = text.replace(
        "`root-cause` is likewise already in\ncontext.",
        "`root-cause` is likewise required context for this role.",
    )
    text = text.replace(
        "the `root-cause` method, which is already in your context",
        "the required `root-cause` method",
    )
    text = re.sub(
        r" \(the variable is substituted with an absolute\s+path; in this plugin's own repo, "
        r"(?:`skills/[a-z0-9-]+/SKILL\.md`|the installed `[a-z0-9-]+` skill)\)",
        "",
        text,
    )
    text = text.replace(
        "The path read is a convention, not an authority boundary: consult the fleet's "
        "platform-facts owner, the installed `prompt-craft` skill's "
        "`references/claude-code-frontmatter.md` resource, for the flag's current enforcement "
        "status; regardless of that status, the checklist's content defers change authority to "
        "you.",
        "The path read is a convention, not an authority boundary. The generated host package "
        "carries its own explicit-invocation control, and the checklist's content still defers "
        "change authority to you.",
    )
    text = text.replace(
        "## Frontmatter quick reference\n\n"
        "Authority lives in frontmatter, not in prose. Before writing or editing any agent or "
        "skill\nfrontmatter, read "
        "[`references/claude-code-frontmatter.md`](references/claude-code-frontmatter.md) —\n"
        "the fleet's single source of truth for Claude Code fields and their traps. Platform "
        "facts and the\ntrap list belong in that file and nowhere else — on drift, fix it there, "
        "never a local copy.",
        "## Host configuration quick reference\n\n"
        "Authority lives in host configuration, not in prose. Use the current official contract\n"
        f"for {host}; this generated adapter does not make Claude fields portable. Read\n"
        "[`references/claude-code-frontmatter.md`](references/claude-code-frontmatter.md) only\n"
        "when editing the canonical Claude definitions.",
    )

    if host == "copilot":
        text = _SLASH_FLEET_TOKEN_RE.sub(lambda match: f"/{match.group('name')}", text)
    elif host == "codex":
        text = _SLASH_FLEET_TOKEN_RE.sub(lambda match: f"${match.group('name')}", text)
    else:
        text = _SLASH_FLEET_TOKEN_RE.sub(lambda match: match.group("name"), text)
    text = _FLEET_TOKEN_RE.sub(lambda match: match.group("name"), text)
    return text


def _copilot_tools(
    fields: dict[str, str], *, guarded: bool
) -> list[str]:
    validator = _validator_module()
    mapped = {
        COPILOT_TOOL_MAP[tool]
        for tool in validator.split_tools(fields.get("tools", ""))
        if tool in COPILOT_TOOL_MAP
    }
    if guarded:
        mapped.discard("execute")
    return [tool for tool in COPILOT_TOOL_ORDER if tool in mapped]


def _has_external_evidence_tools(fields: dict[str, str]) -> bool:
    validator = _validator_module()
    return any(
        tool == "ToolSearch" or tool.startswith("mcp__")
        for tool in validator.split_tools(fields.get("tools", ""))
    )


def _required_skills(fields: dict[str, str]) -> list[str]:
    return [
        entry.strip()
        for entry in fields.get("skills", "").split(",")
        if entry.strip()
    ]


def adapt_agent_contract(text: str, *, name: str, host: str) -> str:
    """Replace Claude-only authority claims in generated agent bodies."""

    host_label = "Codex" if host == "codex" else "Copilot/VS Code"
    # Both callers supply adapt_text output, so Agent-tool terminology is already translated.
    text = text.replace(
        "You hold Write and Edit **to author tests**",
        "You hold edit authority **to author tests**",
    )
    if host == "copilot":
        spawn_boundary = "this profile receives no `agent` tool, so"
    else:
        spawn_boundary = (
            "Codex custom-agent TOML cannot remove inherited subagent authority,\nso the role's "
            "no-spawn rule is cooperative; therefore"
        )
    text = re.sub(
        r"you hold no `Agent`\s+tool, so",
        spawn_boundary,
        text,
    )
    if name == "code-reviewer":
        text = text.replace(
            "Check review comments on recent merged PRs that touched the same files (`gh pr list` "
            "/ `gh pr view` — read-only, on the allowlist) for standing objections that apply "
            "again.",
            "Use the host's read-only GitHub or PR context, when available, to check recent merged "
            "PRs that touched the same files for standing objections that apply again; name the "
            "evidence gap when that context is unavailable.",
        )
        if host == "copilot":
            enforcement = (
                "This profile receives no execute tool, so shell execution is unavailable by "
                "capability."
            )
        else:
            enforcement = (
                "This profile cannot remove inherited shell authority, and its requested sandbox "
                "can be overridden by parent permissions; the no-execution rule is cooperative."
            )
        replacement = (
            "**Inspection only. You may not execute code** — no test runners, build tools, "
            "scripts, or repository validators. Cite the builder's packet or CI evidence; when it "
            "is missing or unconvincing, report that as a finding and name "
            "`verification-engineer` as the independently executed escalation. "
            f"{enforcement} Use read/search inspection and name anything the host cannot expose.\n\n"
            "| Rationalization | Reality |\n"
            "|---|---|\n"
            "| \"Just run the tests to confirm\" | Running repository code is not read-only, "
            "whatever the command looks like. |\n"
            "| \"The host boundary will catch me anyway\" | Capability and sandbox controls do "
            "not make arbitrary code safe to execute. |\n"
            "| A review \"seems to require\" running or changing something | Stop and report that "
            "instead. |\n"
        )
        text = re.sub(
            r"\*\*Your Bash access is for inspection only\..*?"
            r"\| A review \"seems to require\" running or changing something "
            r"\| Stop and report that instead\. \|",
            replacement,
            text,
            flags=re.DOTALL,
        )

    if host == "codex" and name == "application-security-auditor":
        text = re.sub(
            r"Static-first is a deliberate boundary, not a limitation:.*?"
            r"not something you improvise\.",
            "Static-first remains a deliberate mandate: do not run the target's code. Codex\n"
            "custom-agent TOML cannot remove inherited shell authority, so the no-execution rule\n"
            "is cooperative and the caller must provide any required isolation before pointing\n"
            "this role at an untrusted repository. Request execution evidence from the caller\n"
            "instead of improvising it.",
            text,
            count=1,
            flags=re.DOTALL,
        )

    if host == "codex" and name == "researcher":
        text = re.sub(
            r"You cannot access the caller's local or private repository, change anything, or run "
            r"commands\..*?external-research session\.",
            "Keep this session external-only: do not inspect local/private repository content,\n"
            "change files, or use shell execution. Codex custom-agent TOML cannot remove inherited\n"
            "local, shell, or write authority, and its requested sandbox is overridable, so the\n"
            "caller must provide an outer isolation boundary before treating that separation as\n"
            "enforced. Request a provenance-labeled local packet through the caller instead.",
            text,
            count=1,
            flags=re.DOTALL,
        )

    if name == "repository-investigator":
        # The canonical paragraph claims a PreToolUse reader allowlist behind Bash. That hook is
        # Claude-only, so on both other hosts the claim must be replaced, not carried: prose that
        # names a control the host cannot load would read as armor and be nothing.
        if host == "copilot":
            replacement = (
                "Keep the investigation local-only: do not fetch external content or change\n"
                "files. This profile receives no shell/execute tool — Copilot and VS Code cannot\n"
                "scope Claude's per-agent command guard — so gather history evidence through\n"
                "read/search tools and name the commit-history evidence you could not reach. The\n"
                "local-only boundary prevents private source from sharing a subordinate context\n"
                "with fetched external content."
            )
        else:
            replacement = (
                "Keep the investigation local-only and do not fetch external content or change\n"
                "files. Codex custom-agent TOML cannot remove inherited web, shell, or write\n"
                "authority, its requested sandbox is overridable, and the source profile's\n"
                "reader-allowlist command guard does not exist on this host — so every boundary\n"
                "here is cooperative: use the shell only for read-only repository inspection\n"
                "(`git log`, `git blame`, `git show`, `git rev-parse`, search), never for code\n"
                "execution or network access, and let the caller provide an outer isolation\n"
                "boundary before treating that separation as enforced. The provenance rule is\n"
                "part of that cooperation, and it binds harder here than on the source host:\n"
                "git executes code named by a repository's local config — diff drivers under\n"
                "`git log`/`git show`, a `core.fsmonitor` command under even `git status` — so a\n"
                "repository that *arrived* as a directory, archive, or mounted volume gets no git\n"
                "commands at all, step 2's `rev-parse`/`status` included, until your caller states\n"
                "the isolation boundary; inspect it with read/search tools and say why. No command\n"
                "guard backs this on Codex, so nothing but this instruction stands between an\n"
                "arrived repository and its own diff driver."
            )
        # Every substitution here must land exactly once. A zero-match miss (the canonical
        # paragraph reworded without this function updated) would regenerate "clean" adapters
        # that still carry the Claude-only PreToolUse claim on hosts that cannot load that
        # guard — and byte-drift validation cannot catch it, because the committed adapter was
        # produced with the same silent miss (PR #141 review finding).
        text, replaced = re.subn(
            r"Your context is deliberately local-only:.*?fetched external content\.",
            replacement,
            text,
            count=1,
            flags=re.DOTALL,
        )
        if replaced != 1:
            raise ValueError(
                f"repository-investigator {host} rewrite: the local-only boundary paragraph "
                f"anchor was not found ({replaced} matches). The canonical paragraph changed "
                f"without updating adapt_agent_contract, so the generated adapter would "
                f"silently keep a Claude-only enforcement claim this host cannot honor."
            )
        if host == "copilot":
            # The method steps name git commands the guard allows on the source host; this
            # profile holds no shell at all, so an instruction to run them would contradict the
            # boundary the paragraph above just drew. Same must-land rule as above.
            for old, new in (
                (
                    "Name the repository root and the revision — `git rev-parse HEAD`, with\n"
                    "   `git status` to detect a dirty tree; on untrusted provenance both wait "
                    "for the isolation\n"
                    "   boundary above.",
                    "Name the repository root and the revision supplied by the caller or exposed\n"
                    "   by the host context.",
                ),
                (
                    "When the question is \"how did it get this way\" or \"why is this here\", "
                    "history is the evidence:\n"
                    "   `git log`/`git blame` on the region, citing the commit that introduced or "
                    "last changed it.",
                    "When the question is \"how did it get this way\" or \"why is this here\", "
                    "history is the evidence:\n"
                    "   use the host's read-only history context when available, and name the "
                    "commit-history\n"
                    "   evidence you could not reach.",
                ),
            ):
                if old not in text:
                    raise ValueError(
                        "repository-investigator copilot rewrite: a method-step anchor was not "
                        "found; the canonical step changed without updating "
                        "adapt_agent_contract, so the no-shell profile would instruct git "
                        "commands it cannot run."
                    )
                text = text.replace(old, new)

    if host == "codex" and name == "verification-engineer":
        text = re.sub(
            r"Your tool list is the platform-enforced boundary;.*?"
            r"voids your independence along with your verdict\.",
            "Effective authority comes from the parent session and its requested sandbox; Codex\n"
            "custom-agent TOML cannot reproduce the canonical per-role tool list. This role's\n"
            "mandate permits edits only to author tests, but that test-only boundary is\n"
            "cooperative because no tool layer distinguishes a test path from product code. Any\n"
            "edit outside test code voids your independence along with your verdict.",
            text,
            count=1,
            flags=re.DOTALL,
        )

    if host == "codex" and name == "multi-agent-architect":
        text = text.replace(
            "- **Tools are authority.** An agent's tool list encodes its mandate: reviewers can't "
            "edit, researchers can't write. Enforce roles at the tool layer, not with prose.",
            "- **Effective capabilities are authority.** Use each target host's structural tool,\n"
            "  sandbox, permission, or isolation controls to match the mandate. Codex custom-agent\n"
            "  TOML has no per-agent tool list, so a reviewer-no-edit or researcher-no-write rule\n"
            "  needs a stronger outer boundary; prose alone does not enforce it.",
        )

    if name == "principal-engineer":
        if host == "copilot":
            inspection = (
                "This profile has no execute tool; use read/search for inspection and name "
                "evidence the host cannot expose."
            )
        else:
            inspection = (
                "Codex still exposes shell execution inside the workspace sandbox, but this role "
                "must not run builds, tests, or scripts; use read/search for inspection and name "
                "evidence the host cannot expose."
            )
        replacement = (
            "Your edit authority covers exactly these artifact classes: design docs, ADRs and "
            "decision records, plans, and risk registers in the repository's documentation home "
            "— never source files, configs, tests, or scripts. "
            f"{inspection} The document-only edit boundary remains cooperative, so when a task "
            "pushes you toward writing code, stop and hand it down instead."
        )
        text = re.sub(
            r"Your Write grant covers exactly these artifact classes:.*?"
            r"The Write boundary stays cooperative — no tool boundary distinguishes a design doc "
            r"from a source file — so when a task pushes you toward writing code, stop and hand it "
            r"down instead\.",
            replacement,
            text,
            flags=re.DOTALL,
        )

    if name == "distinguished-architect":
        if host == "copilot":
            inspection = (
                "This profile has no execute tool; use read/search for inspection and name "
                "evidence the host cannot expose."
            )
        else:
            inspection = (
                "Codex still exposes shell execution inside the workspace sandbox, but this role "
                "must not run builds, tests, or scripts; use read/search for inspection and name "
                "evidence the host cannot expose."
            )
        replacement = (
            "Your edit authority covers exactly those document classes in the repository's "
            "documentation home — never source files, configs, tests, or scripts. "
            f"{inspection} The document-only edit boundary remains cooperative, so when an "
            "engagement pushes you toward writing code, hand it down the ladder instead."
        )
        text = re.sub(
            r"Your Write grant covers exactly those document classes,.*?"
            r"The Write mandate stays cooperative — no tool boundary distinguishes a doc from "
            r"code — so when an engagement pushes you toward writing code, hand it down the "
            r"ladder instead\.",
            replacement,
            text,
            flags=re.DOTALL,
        )

    if name == "prompt-engineer":
        text = text.replace(
            "**Tools are authority.** When authoring agents, scope the tool list to the mandate "
            "instead of writing \"do not edit files\" in prose. Runtime constraints hold; "
            "instructions bend.",
            "**Runtime capabilities are authority.** When authoring agents, use the target host's "
            "tool, sandbox, and permission controls to match the mandate instead of relying on "
            "prose. Runtime constraints hold; instructions bend.",
        )
        configuration_guidance = (
            "## Host-specific configuration\n\n"
            "Authority lives in host configuration, not prose, and the field set moves with the "
            f"platform. Before editing {host_label} agent or skill metadata, read that host's "
            "current official contract. When editing a canonical source definition instead, also "
            "consult the installed `prompt-craft` skill's source-host frontmatter reference. Name "
            "the contract used in the change packet."
            if host == "codex"
            else "## Host-specific configuration\n\n"
            "Authority lives in host configuration, not prose, and the field set moves with the "
            f"platform. Before editing {host_label} agent or skill metadata, read that host's "
            "current official contract. Use the installed `prompt-craft` skill's "
            "`references/claude-code-frontmatter.md` resource only when the target is a canonical "
            "Claude definition. Name the contract used in the change packet."
        )
        text = re.sub(
            r"## Claude Code specifics\n\n.*?(?=\n## Voice)",
            configuration_guidance,
            text,
            flags=re.DOTALL,
        )

    if name == "multi-agent-architect":
        if host == "codex":
            text = re.sub(
                r"and, when the target is Claude Code, the actual agent and `SKILL\.md` files "
                r"\(`\.claude/agents/\*\.md` in a project, `agents/\*\.md` in a plugin — "
                r"the reference below settles which\), written to match",
                "and, when the target is Codex, the actual `.codex/agents/*.toml` profiles and "
                "installed skills, written to match",
                text,
            )
        frontmatter_guidance = (
            f"Before writing any frontmatter, read the current {host_label} contract. When "
            "editing a canonical source definition instead, also consult the installed "
            "`prompt-craft` skill's source-host frontmatter reference, so authority and ignored "
            "fields come from the target host rather than memory; name the sources in your "
            "packet."
            if host == "codex"
            else f"Before writing any frontmatter, read the current {host_label} contract — or "
            "the installed `prompt-craft` skill's `references/claude-code-frontmatter.md` "
            "resource when the target is Claude — so authority and ignored fields come from the "
            "target host rather than memory; name the sources in your packet."
        )
        text = re.sub(
            r"Before writing any frontmatter, read the fleet's single source of truth — .*?"
            r"name it in your packet\.",
            frontmatter_guidance,
            text,
            flags=re.DOTALL,
        )

    return text


def render_copilot_agent(source: Path, *, guarded_names: set[str]) -> str:
    fields, body, _ = _definition_parts(source)
    name = fields["name"]
    guarded = name in guarded_names
    tools = _copilot_tools(fields, guarded=guarded)
    description = adapt_text(fields["description"], "copilot")
    instructions = adapt_agent_contract(
        adapt_text(body.rstrip(), "copilot"),
        name=name,
        host="copilot",
    )

    adapter_lines = [
        "## Host adapter contract",
        "",
        "This generated profile runs on GitHub Copilot and VS Code. Fleet component names are",
        "bare on these hosts; resolve them from the installed plugin using the host's agent or",
        "skill picker.",
    ]
    if guarded:
        adapter_lines.extend(
            [
                "",
                "This profile deliberately receives no shell/execute tool. Claude's source profile",
                "uses a session-wide read-only Bash guard, but Copilot and VS Code PreToolUse",
                "payloads do not identify the active agent. Treat shell inspection as unavailable",
                "and use read/search tools instead.",
            ]
        )
    if _has_external_evidence_tools(fields):
        adapter_lines.extend(
            [
                "",
                "Claude-specific MCP tool identifiers are not promised by this adapter. Use an",
                "equivalent connected evidence tool only when the host actually exposes it, keep",
                "its provenance distinct, and label the gap when it is unavailable.",
            ]
        )
    required_skills = _required_skills(fields)
    if required_skills:
        rendered_skills = ", ".join(f"`{skill}`" for skill in required_skills)
        adapter_lines.extend(
            [
                "",
                f"Claude's source profile preloads {rendered_skills}. This host cannot encode that",
                "Claude frontmatter contract; load every listed installed skill before following",
                "the role.",
            ]
        )

    return (
        "---\n"
        f"name: {json.dumps(name, ensure_ascii=False)}\n"
        f"description: {json.dumps(description, ensure_ascii=False)}\n"
        f"tools: {json.dumps(tools)}\n"
        "---\n\n"
        f"<!-- {GENERATED_MARKER} -->\n\n"
        + "\n".join(adapter_lines)
        + "\n\n"
        + instructions
        + "\n"
    )


def _codex_agent_parts(source: Path) -> tuple[dict[str, str], str, str, str, str]:
    """Return source metadata plus one shared Codex authority contract."""

    validator = _validator_module()
    fields, body, _ = _definition_parts(source)
    name = fields["name"]
    tools = set(validator.split_tools(fields.get("tools", "")))
    sandbox_mode = "workspace-write" if tools & validator.WRITE_TOOLS else "read-only"
    description = adapt_text(fields["description"], "codex")
    instructions = adapt_agent_contract(
        adapt_text(body.rstrip(), "codex"),
        name=name,
        host="codex",
    )
    instructions = instructions.replace(
        "(`AGENTS.md`, `CLAUDE.md`, or the current host's project-instruction equivalent)",
        "(`AGENTS.md` or the current host's project-instruction equivalent)",
    )
    instructions = instructions.replace(
        "Record it in the repository's existing project-instruction file; prefer a portable "
        "`AGENTS.md`, and use `CLAUDE.md` when that is the repository's established convention;",
        "Record it in the repository's existing project-instruction file; prefer a portable "
        "`AGENTS.md`, and follow the established equivalent when the host uses another file;",
    )

    adapter_lines = [
        "Host adapter contract:",
        "- This generated profile is both a source-host project agent and an official Codex",
        "  import source. Fleet component names are bare; in Codex, select skills with the",
        "  skill picker or `$name` syntax.",
        "- Parent session permissions can override this requested sandbox; live permission changes",
        "  and full-access mode are reapplied to child agents.",
        "- The Markdown staging source carries a source-host tool list. Codex custom-agent TOML",
        "  does not provide a per-agent tool allowlist: shell, MCP, skill, and subagent tools may",
        "  remain inherited, so narrower no-shell or no-spawn rules are cooperative unless an",
        "  outer boundary disables those capabilities.",
    ]
    if sandbox_mode == "read-only":
        adapter_lines.extend(
            [
                "- This profile requests `sandbox_mode = \"read-only\"` to match the canonical",
                "  no-write mandate. If the parent grants write authority, that mandate becomes",
                "  cooperative rather than enforced by this profile.",
            ]
        )
    else:
        adapter_lines.extend(
            [
                "- This profile requests `sandbox_mode = \"workspace-write\"` for ordinary local",
                "  workspace changes. Any narrower document-only, test-only, approval, or",
                "  live-effect boundary remains cooperative and must be stated honestly.",
            ]
        )
    if _has_external_evidence_tools(fields):
        adapter_lines.extend(
            [
                "- Source-specific MCP tool IDs are not bundled here. Use equivalent inherited",
                "  evidence tools only when present, preserve provenance, and label unavailable",
                "  evidence instead of inventing it.",
            ]
        )
    required_skills = _required_skills(fields)
    if required_skills:
        rendered_skills = ", ".join(f"`${skill}`" for skill in required_skills)
        adapter_lines.extend(
            [
                f"- The source Markdown profile preloads {rendered_skills}. Invoke every listed",
                "  installed skill before following the role; custom-agent TOML does not package",
                "  the source `skills:` frontmatter.",
            ]
        )

    full_instructions = "\n".join(adapter_lines) + "\n\n" + instructions
    return fields, name, sandbox_mode, description, full_instructions


def render_codex_agent(source: Path) -> str:
    _, name, sandbox_mode, description, full_instructions = _codex_agent_parts(source)
    if "'''" in full_instructions:
        raise ValueError(f"{source}: body contains TOML multiline-literal delimiter")

    return (
        f"# {GENERATED_MARKER}\n"
        f"name = {json.dumps(name, ensure_ascii=False)}\n"
        f"description = {json.dumps(description, ensure_ascii=False)}\n"
        f"sandbox_mode = {json.dumps(sandbox_mode)}\n"
        "developer_instructions = '''\n"
        f"{full_instructions}\n"
        "'''\n"
    )


def render_codex_import_agent(source: Path) -> str:
    """Render Markdown that Codex ``/import`` converts into the shared TOML contract."""

    fields, name, sandbox_mode, description, full_instructions = _codex_agent_parts(source)
    permission_mode = "acceptEdits" if sandbox_mode == "workspace-write" else "readOnly"
    lines = [
        "---",
        f"# {GENERATED_MARKER}",
        f"name: {json.dumps(name, ensure_ascii=False)}",
        f"description: {description}",
        f"tools: {json.dumps(fields.get('tools', ''), ensure_ascii=False)}",
        f"permissionMode: {permission_mode}",
    ]
    if model := fields.get("model"):
        lines.append(f"model: {json.dumps(model, ensure_ascii=False)}")
    if color := fields.get("color"):
        lines.append(f"color: {json.dumps(color, ensure_ascii=False)}")
    required_skills = _required_skills(fields)
    if required_skills:
        lines.append(f"skills: {json.dumps(required_skills, ensure_ascii=False)}")
    lines.extend(["---", "", full_instructions, ""])
    return "\n".join(lines)


def _portable_frontmatter(
    lines: list[str],
    fields: dict[str, str],
    *,
    host: str,
) -> tuple[list[str], bool, bool]:
    """Render the canonical scalar subset as YAML accepted by both target hosts."""

    if host not in {"codex", "copilot"}:
        raise ValueError(f"unknown skill adapter host {host!r}")

    output: list[str] = []
    explicit_only = False
    had_tool_deny = False
    for line in lines:
        match = _FRONTMATTER_LINE_RE.match(line)
        if match is None:
            raise ValueError(f"frontmatter line is outside the supported scalar subset: {line!r}")
        key = match.group("key")
        if key == "disallowed-tools":
            had_tool_deny = True
            continue
        if key == "disable-model-invocation":
            explicit_only = fields.get(key, "").lower() == "true"
            if host == "copilot" and explicit_only:
                output.append("disable-model-invocation: true")
            continue

        value = adapt_text(fields.get(key, ""), host)
        output.append(f"{key}: {json.dumps(value, ensure_ascii=False)}")
    return output, explicit_only, had_tool_deny


def _portable_readonly_body(body: str) -> str:
    """Remove Claude-only claims from skills whose source has a tool deny."""

    body = re.sub(
        r"All checks are read-only\. `disallowed-tools` removes Write and Edit while this skill "
        r"is active,\s+but Bash can still mutate",
        "All checks are read-only. This portable adapter has no cross-host write-tool deny, and "
        "shell access can still mutate",
        body,
    )
    body = re.sub(
        r"Whether you were invoked directly from the main session or under `homelab-platform`, "
        r"the reviewer's Bash guard does not cover this skill \(that hook keys on guarded "
        r"\*agent\* identities, and the main loop carries none at all\) — the read-only-ness here "
        r"is cooperative, not enforced\. `NotebookEdit` is in `disallowed-tools` for the same "
        r"reason as Write and Edit: it is a write tool, and a denylist that names only the obvious "
        r"two leaves the third\.",
        "The parent host's sandbox or permission profile is the only hard boundary here; the "
        "skill's read-only posture is cooperative, and no write-capable tool is within its mandate.",
        body,
    )
    body = re.sub(
        r"The\s+read-only-ness here is cooperative, not enforced \(the reviewer's Bash guard keys "
        r"on guarded\s+\*agent\* identities, not skills\)\.",
        "The parent host's sandbox or permission profile is the only hard boundary here; the "
        "skill's read-only posture is cooperative.",
        body,
    )
    return body


def adapt_agent_security_reference(text: str, *, host: str) -> str:
    if host == "copilot":
        tool_section = """## Tool grants are the actual security boundary

- Use only documented Copilot/VS Code tool aliases in an explicit `tools:` list. Unknown names are
  ignored, so a plausible-looking alias is not a restriction until the host accepts it.
- For a read-only role, omit `edit`, `execute`, and `web`; prose does not narrow a granted tool.
- Shell/execute is the universal escape hatch. Copilot and VS Code `PreToolUse` input does not
  identify the active custom agent, and VS Code ignores hook matchers, so do not claim an
  agent-scoped shell guard. Remove `execute` or isolate the role instead.
- Keep private data, untrusted input, and outbound or write authority out of one context."""
    else:
        tool_section = """## Parent permissions determine effective authority

- Standalone Codex custom agents request `sandbox_mode` and inherit session configuration; they do
  not carry a per-agent Claude or Copilot `tools:` allowlist.
- Parent live permission changes and full-access mode can override the profile's requested sandbox
  and are reapplied to child agents. Use `sandbox_mode = "read-only"` as a safer default for
  investigative roles, never as proof of an immutable no-write boundary.
- Shell execution can still run untrusted code even when filesystem writes are denied. If a role
  must not execute code, state that cooperative limit and remove untrusted inputs or shell
  authority at a stronger outer boundary when available.
- Codex plugins package skills but not custom-agent TOML, so review the standalone agent and plugin
  skill surfaces as separate install artifacts."""

    text = re.sub(
        r"## Tool grants are the actual security boundary\n.*?"
        r"(?=## Content boundaries in the prompt itself)",
        tool_section + "\n\n",
        text,
        flags=re.DOTALL,
    )
    text = text.replace(
        "2. Does its `tools:` list say exactly what it can do — with nothing inherited and no "
        "fake scoping?\n"
        "3. If it holds `Bash` or a write tool, what enforces the limit its prose claims?",
        "2. Does the host configuration grant exactly the authority the role needs, with no "
        "plausible-looking but inert\n   restriction?\n"
        "3. What structural capability, sandbox, or isolation boundary enforces every limit the\n"
        "   prose claims?",
    )
    return text


def adapt_tools_reference(text: str, *, host: str) -> str:
    if host == "copilot":
        mandate_section = """## The tool list is the mandate

An agent's capabilities are its tools, not its prose. Use the least documented native aliases that
make the job possible and enumerate them explicitly. Unknown names are ignored. A read-only
investigator normally needs `read` and `search`, with no `edit`, `execute`, or `web`; pair each
additional grant with its reason in the agent body."""
    else:
        mandate_section = """## Parent permissions and inherited configuration are the mandate

Codex custom-agent TOML does not use Claude or Copilot `tools:` frontmatter. Start investigative
roles with a requested `sandbox_mode = "read-only"`, review inherited shell, MCP, skill, and
subagent authority, and remember that parent permission changes can override the profile default.
Prose can narrow a mandate cooperatively, but it cannot remove a capability that the runtime still
exposes."""

    text = re.sub(
        r"## The tool list is the mandate\n.*?(?=## When to promote a Bash invocation into a real "
        r"tool)",
        mandate_section + "\n\n",
        text,
        flags=re.DOTALL,
    )
    text = text.replace(
        "## When to promote a Bash invocation into a real tool",
        "## When to promote a shell invocation into a real tool",
    )
    text = text.replace(
        "refuse the rest; `Bash` cannot be narrowed after the fact.",
        "refuse the rest; a general shell cannot be narrowed after the fact.",
    )
    text = text.replace(
        "Keep it as `Bash` when the work is genuinely ad-hoc exploration",
        "Keep it as a shell command when the work is genuinely ad-hoc exploration",
    )
    return text


def adapt_host_resource(text: str, *, relative: Path, host: str) -> str:
    if relative == Path("prompt-craft/references/agent-security.md"):
        return adapt_agent_security_reference(text, host=host)
    if relative == Path("prompt-craft/references/tools.md"):
        return adapt_tools_reference(text, host=host)
    return text


def render_portable_skill(source: Path, *, host: str) -> tuple[str, bool]:
    fields, body, frontmatter = _definition_parts(source)
    portable_frontmatter, explicit_only, had_tool_deny = _portable_frontmatter(
        frontmatter,
        fields,
        host=host,
    )
    portable_body = adapt_text(body.rstrip(), host)
    if had_tool_deny:
        portable_body = _portable_readonly_body(portable_body)

    notes = [
        f"<!-- {GENERATED_MARKER} -->",
        "",
        f"> **{host.title()} adapter:** Fleet component names are bare in this generated copy.",
        "> Resolve them from the installed plugin using the host's agent or skill picker; do not add",
        "> Claude's plugin namespace.",
    ]
    if explicit_only:
        if host == "copilot":
            notes.append("> This skill is explicit-only through Copilot's frontmatter switch.")
        else:
            notes.append(
                "> This skill is explicit-only through the generated `agents/openai.yaml` policy."
            )
    if had_tool_deny:
        notes.extend(
            [
                "> No single skill-level tool deny is portable across these hosts. The read-only",
                "> mandate is cooperative and the parent host's sandbox or permission profile is",
                "> the enforcement boundary.",
            ]
        )

    return (
        "---\n"
        + "\n".join(portable_frontmatter)
        + "\n---\n\n"
        + "\n".join(notes)
        + "\n\n"
        + portable_body
        + "\n",
        explicit_only,
    )


def render_codex_skill_policy(fields: dict[str, str]) -> bytes:
    """Render the Codex-only policy and required interface metadata for one explicit skill."""

    name = fields["name"]
    description = adapt_text(fields["description"], "codex")
    short_description = description
    if len(short_description) > 100:
        shortened = short_description[:97].rsplit(" ", 1)[0].rstrip()
        short_description = (shortened or short_description[:97].rstrip()) + "..."
    display_name = name.replace("-", " ").title()
    return (
        "interface:\n"
        f"  display_name: {json.dumps(display_name, ensure_ascii=False)}\n"
        f"  short_description: {json.dumps(short_description, ensure_ascii=False)}\n"
        "policy:\n"
        "  allow_implicit_invocation: false\n"
    ).encode("utf-8")


def _guarded_names(root: Path) -> set[str]:
    validator = _validator_module()
    return set(validator.load_guard(root).GUARDED_AGENT_NAMES)


def _is_runtime_byproduct(path: Path) -> bool:
    """Use the shared fleet predicate for execution residue, not a second vocabulary."""

    return bool(_validator_module().is_runtime_byproduct(path))


def _is_link_or_reparse_point(path: Path) -> bool:
    """Recognize links and Windows reparse points before any read or recursive removal."""

    if path.is_symlink():
        return True
    is_junction = getattr(path, "is_junction", None)
    if is_junction is not None and is_junction():
        return True
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return False
    attributes = getattr(metadata, "st_file_attributes", 0)
    reparse_attribute = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0)
    return bool(reparse_attribute and attributes & reparse_attribute)


def _assert_no_generated_path_indirection(path: Path, *, operation: str) -> None:
    """Fail before a generated-tree operation can cross a filesystem boundary."""

    if _is_link_or_reparse_point(path):
        consequence = (
            "Recursive replacement could delete a different tree."
            if operation == "replace"
            else "Validation could read or certify a different tree."
        )
        raise ValueError(
            f"refusing to {operation} generated path through a link, junction, or reparse "
            f"point: {path}. {consequence}"
        )


def _raise_directory_walk_error(error: OSError) -> None:
    """Make an unreadable generated subtree fail validation instead of disappearing from it."""

    raise error


def _assert_canonical_source_path(path: Path, repository_root: Path) -> None:
    """Reject a canonical resource that escapes through any link-like path component."""

    resolved_root = repository_root.resolve()
    lexical_path = Path(os.path.abspath(path))
    if not lexical_path.is_relative_to(resolved_root):
        raise ValueError(f"canonical source path is outside repository: {lexical_path}")

    current = resolved_root
    for part in lexical_path.relative_to(resolved_root).parts:
        current /= part
        if _is_link_or_reparse_point(current):
            raise ValueError(
                "canonical source path crosses a link, junction, or reparse point: "
                f"{current}. Generation would read or package bytes from a different location."
            )

    resolved_path = lexical_path.resolve(strict=True)
    if not resolved_path.is_relative_to(resolved_root):
        raise ValueError(
            f"canonical source path resolves outside repository: {lexical_path}"
        )


def _canonical_skill_files(root: Path) -> list[Path]:
    """Enumerate canonical skill resources without following directory indirection."""

    resolved_root = root.resolve()
    skills_root = resolved_root / "skills"
    _assert_canonical_source_path(skills_root, resolved_root)
    if not skills_root.is_dir():
        raise ValueError(f"{skills_root}: canonical skill root is not a directory")

    files: list[Path] = []
    for directory_name, directory_names, file_names in os.walk(
        skills_root,
        topdown=True,
        followlinks=False,
    ):
        directory = Path(directory_name)
        _assert_canonical_source_path(directory, resolved_root)
        directory_names.sort()
        for child_name in directory_names:
            child = directory / child_name
            _assert_canonical_source_path(child, resolved_root)
            if not child.is_dir():
                raise ValueError(f"{child}: canonical skill path is not a directory")
        for file_name in sorted(file_names):
            source = directory / file_name
            _assert_canonical_source_path(source, resolved_root)
            if not source.is_file():
                raise ValueError(f"{source}: canonical skill resource is not a regular file")
            files.append(source)
    return files


def _repository_tracked_files(root: Path) -> set[Path] | None:
    """Return tracked paths, or None when Git cannot prove which residue is untracked."""

    try:
        top_level = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--show-toplevel"],
            capture_output=True,
            check=False,
            timeout=10,
        )
        if top_level.returncode:
            return None
        discovered_root = Path(os.fsdecode(top_level.stdout).strip()).resolve()
        if discovered_root != root.resolve():
            return None
        result = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z"],
            capture_output=True,
            check=False,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode:
        return None
    return {
        Path(os.fsdecode(raw_path))
        for raw_path in result.stdout.split(b"\0")
        if raw_path
    }


def _canonical_resource_bytes(source: Path) -> bytes:
    """Serialize declared text deterministically while preserving every other resource byte.

    Git normally checks the fleet's text formats out as LF, but a checkout whose attributes were
    applied late can temporarily contain CRLF while its generated copies still contain LF. Raw
    copying then reports host-only drift. Restrict normalization to the repository's explicitly
    textual suffixes: content sniffing could silently corrupt a binary file that happens to decode.
    """

    raw = source.read_bytes()
    if source.suffix.lower() not in _TEXT_RESOURCE_SUFFIXES:
        return raw
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError(
            f"{source}: declared text resource is not valid UTF-8; generation cannot produce "
            "checkout-independent bytes"
        ) from exc
    return text.replace("\r\n", "\n").replace("\r", "\n").encode("utf-8")


def expected_outputs(root: Path) -> dict[Path, bytes]:
    """Return every generated file, keyed by repository-relative path."""

    root = root.resolve()
    outputs: dict[Path, bytes] = {}
    guarded_names = _guarded_names(root)
    agents_root = root / "agents"
    _assert_canonical_source_path(agents_root, root)
    for source in sorted(agents_root.glob("*.md")):
        _assert_canonical_source_path(source, root)
        outputs[COPILOT_AGENTS / f"{source.stem}.agent.md"] = render_copilot_agent(
            source, guarded_names=guarded_names
        ).encode("utf-8")
        outputs[CODEX_AGENTS / f"{source.stem}.toml"] = render_codex_agent(source).encode(
            "utf-8"
        )
        outputs[CLAUDE_IMPORT_AGENTS / f"{source.stem}.md"] = (
            render_codex_import_agent(source).encode("utf-8")
        )

    skills_root = root / "skills"
    canonical_skill_files = _canonical_skill_files(root)
    for host, target_root in (
        ("copilot", COPILOT_SKILLS),
        ("codex", CODEX_SKILLS),
    ):
        for source in canonical_skill_files:
            relative = source.relative_to(skills_root)
            if _is_runtime_byproduct(relative):
                continue
            target = target_root / relative
            if source.name == "SKILL.md":
                fields, _, _ = _definition_parts(source)
                rendered, explicit_only = render_portable_skill(source, host=host)
                outputs[target] = rendered.encode("utf-8")
                if host == "codex" and explicit_only:
                    outputs[target.parent / "agents" / "openai.yaml"] = (
                        render_codex_skill_policy(fields)
                    )
            elif source.suffix.lower() == ".md" and relative != CLAUDE_REFERENCE:
                adapted_resource = adapt_host_resource(
                    adapt_text(source.read_text(encoding="utf-8"), host),
                    relative=relative,
                    host=host,
                )
                outputs[target] = (
                    f"<!-- {GENERATED_MARKER} -->\n\n"
                    + adapted_resource.rstrip()
                    + "\n"
                ).encode("utf-8")
            else:
                outputs[target] = _canonical_resource_bytes(source)
    return outputs


def _actual_generated_files(
    root: Path,
    *,
    tracked_files: set[Path] | None,
) -> set[Path]:
    root = root.resolve()
    paths: set[Path] = set()
    for relative_root in GENERATED_ROOTS:
        directory = _safe_generated_root(root, relative_root, operation="inspect")
        if not directory.is_dir():
            continue
        for directory_name, directory_names, file_names in os.walk(
            directory,
            topdown=True,
            onerror=_raise_directory_walk_error,
            followlinks=False,
        ):
            current = Path(directory_name)
            _assert_no_generated_path_indirection(current, operation="inspect")
            directory_names.sort()
            for child_name in directory_names:
                _assert_no_generated_path_indirection(
                    current / child_name,
                    operation="inspect",
                )
            for file_name in sorted(file_names):
                path = current / file_name
                _assert_no_generated_path_indirection(path, operation="inspect")
                if not path.is_file():
                    continue
                repository_relative = path.relative_to(root)
                if (
                    _is_runtime_byproduct(path.relative_to(directory))
                    and tracked_files is not None
                    and repository_relative not in tracked_files
                ):
                    continue
                paths.add(repository_relative)
    return paths


def validate_generated_outputs(root: Path) -> list[str]:
    """Report missing, extra, or stale generated files."""

    if not (root / ".claude-plugin" / "plugin.json").is_file():
        return []

    issues: list[str] = []
    try:
        expected = expected_outputs(root)
    except (OSError, ValueError) as exc:
        return [f"{root}: cannot render platform adapters from canonical sources: {exc}"]

    try:
        actual = _actual_generated_files(
            root,
            tracked_files=_repository_tracked_files(root),
        )
    except (OSError, ValueError) as exc:
        return [f"{root}: cannot inspect generated platform adapters: {exc}"]
    for relative in RETIRED_GENERATED_ROOTS:
        retired = root / relative
        if retired.exists():
            issues.append(
                f"{retired}: retired generated adapter root still exists. Both the old shared "
                f"copy and the host-specific copies could be reviewed or packaged as authoritative; "
                f"run `python scripts/generate_platform_adapters.py --write`."
            )
    for relative in sorted(set(expected) - actual):
        issues.append(
            f"{root / relative}: missing generated platform adapter. Copilot, VS Code, or Codex "
            f"would silently lose this component; run "
            f"`python scripts/generate_platform_adapters.py --write`."
        )
    for relative in sorted(actual - set(expected)):
        issues.append(
            f"{root / relative}: stale generated platform adapter has no canonical source. A "
            f"removed component would remain loadable on another host; regenerate the adapters."
        )
    for relative in sorted(set(expected) & actual):
        path = root / relative
        if path.read_bytes() != expected[relative]:
            issues.append(
                f"{path}: generated platform adapter drifted from its canonical source. Editing "
                f"the copy creates host-dependent behavior with no visible error; regenerate it."
            )
    return issues


def _read_manifest(path: Path) -> tuple[dict | None, list[str]]:
    if not path.is_file():
        return None, [f"{path}: missing platform plugin manifest"]
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        return None, [f"{path}: unreadable platform plugin manifest: {exc}"]
    if not isinstance(data, dict):
        return None, [f"{path}: platform plugin manifest must be a JSON object"]
    return data, []


def validate_platform_contracts(root: Path) -> list[str]:
    """Validate manifest parity and host-specific component routing."""

    claude_path = root / ".claude-plugin" / "plugin.json"
    if not claude_path.is_file():
        return []

    copilot_path = root / "plugin.json"
    codex_path = root / CODEX_PLUGIN_ROOT / ".codex-plugin" / "plugin.json"
    claude, issues = _read_manifest(claude_path)
    copilot, read_issues = _read_manifest(copilot_path)
    issues.extend(read_issues)
    codex, read_issues = _read_manifest(codex_path)
    issues.extend(read_issues)
    if claude is None or copilot is None or codex is None:
        return issues

    for field in IDENTITY_FIELDS:
        expected = claude.get(field)
        for label, path, manifest in (
            ("Copilot/VS Code", copilot_path, copilot),
            ("Codex", codex_path, codex),
        ):
            if manifest.get(field) != expected:
                issues.append(
                    f"{path}: {label} manifest field {field!r} differs from the Claude manifest. "
                    f"One release would install under conflicting identity or version metadata."
                )

    for field, expected in COPILOT_COMPONENTS.items():
        if copilot.get(field) != expected:
            issues.append(
                f"{copilot_path}: {field!r} must be {expected!r}. Copilot/VS Code must load the "
                f"generated authority adapter, not Claude's plausible-but-incompatible default."
            )
    for field, expected in CODEX_COMPONENTS.items():
        if codex.get(field) != expected:
            issues.append(
                f"{codex_path}: {field!r} must be {expected!r}. Codex must load the portable "
                f"skill bundle from its isolated plugin root."
            )
    codex_interface = codex.get("interface")
    required_interface_fields = {
        "displayName",
        "shortDescription",
        "longDescription",
        "developerName",
        "category",
    }
    if (
        not isinstance(codex_interface, dict)
        or not required_interface_fields.issubset(codex_interface)
        or not all(
            isinstance(codex_interface[field], str) and codex_interface[field].strip()
            for field in required_interface_fields
            if isinstance(codex_interface, dict)
        )
        or not isinstance(
            codex_interface.get("defaultPrompt") if isinstance(codex_interface, dict) else None,
            list,
        )
        or not isinstance(
            codex_interface.get("capabilities") if isinstance(codex_interface, dict) else None,
            list,
        )
    ):
        issues.append(
            f"{codex_path}: Codex manifest interface is missing required presentation fields. "
            f"Codex plugin ingestion rejects an incomplete marketplace card outside this repo's CI."
        )
    if "agents" in codex:
        issues.append(
            f"{codex_path}: Codex plugin manifests do not package custom agents. Keep standalone "
            f"TOML under .codex/agents and document the separate sync step; an 'agents' manifest "
            f"field would read as distribution while loading nothing."
        )
    if "hooks" in codex:
        issues.append(
            f"{codex_path}: Codex must not load the Claude hook through a manifest override. Keep "
            f"its nested plugin root hook-free and express requested agent sandbox defaults only "
            f"in standalone TOML."
        )

    hook_value = copilot.get("hooks")
    if isinstance(hook_value, str) and hook_value.startswith("./"):
        hook_path = root / hook_value.removeprefix("./")
        try:
            hook_config = json.loads(hook_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            issues.append(f"{hook_path}: unreadable Copilot/VS Code hook override: {exc}")
        else:
            if hook_config.get("hooks") != {}:
                issues.append(
                    f"{hook_path}: Copilot/VS Code hook override must contain an empty hooks "
                    f"object. The Claude guard scopes on agent_type, which these hosts do not send "
                    f"on PreToolUse."
                )
            if "readonly-guard.py" in hook_path.read_text(encoding="utf-8"):
                issues.append(
                    f"{hook_path}: Copilot/VS Code hook override references the Claude read-only "
                    f"guard even though the host payload cannot identify the active agent."
                )

    codex_default_hook = root / CODEX_PLUGIN_ROOT / "hooks" / "hooks.json"
    if codex_default_hook.exists():
        issues.append(
            f"{codex_default_hook}: isolated Codex plugin root must be hook-free. A default hook "
            f"would bypass the host-specific sandbox design."
        )

    marketplace_path = root / ".claude-plugin" / "marketplace.json"
    try:
        marketplace = json.loads(marketplace_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        issues.append(f"{marketplace_path}: unreadable cross-host marketplace manifest: {exc}")
    else:
        entries = [
            entry
            for entry in marketplace.get("plugins", [])
            if entry.get("name") == claude.get("name")
        ]
        if len(entries) != 1:
            issues.append(
                f"{marketplace_path}: expected exactly one entry for {claude.get('name')!r}; "
                f"Claude marketplace would lose or duplicate the plugin."
            )
        elif entries[0].get("version") != claude.get("version"):
            issues.append(
                f"{marketplace_path}: plugin version differs from the platform manifests. "
                f"Marketplace caches could serve changed files under stale release metadata."
            )

    codex_marketplace_path = root / ".agents" / "plugins" / "marketplace.json"
    try:
        codex_marketplace = json.loads(codex_marketplace_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        issues.append(f"{codex_marketplace_path}: unreadable Codex marketplace manifest: {exc}")
    else:
        codex_entries = [
            entry
            for entry in codex_marketplace.get("plugins", [])
            if entry.get("name") == claude.get("name")
        ]
        expected_source = {
            "source": "local",
            "path": "./plugins/sde-agents",
        }
        if len(codex_entries) != 1:
            issues.append(
                f"{codex_marketplace_path}: expected exactly one Codex marketplace entry for "
                f"{claude.get('name')!r}. Repository installation would not find the nested plugin."
            )
        elif codex_entries[0].get("source") != expected_source:
            issues.append(
                f"{codex_marketplace_path}: Codex marketplace source must be {expected_source!r}. "
                f"The nested plugin isolates Codex from Claude's incompatible default hook."
            )
        if len(codex_entries) == 1:
            entry = codex_entries[0]
            policy = entry.get("policy")
            valid_policy = (
                isinstance(policy, dict)
                and policy.get("installation")
                in {"NOT_AVAILABLE", "AVAILABLE", "INSTALLED_BY_DEFAULT"}
                and policy.get("authentication") in {"ON_INSTALL", "ON_USE"}
            )
            if (
                not valid_policy
                or not isinstance(entry.get("category"), str)
                or not entry["category"].strip()
            ):
                issues.append(
                    f"{codex_marketplace_path}: Codex marketplace entry requires installation "
                    f"policy, authentication timing, and category. An incomplete entry fails only "
                    f"when a consumer tries to install it."
                )

    return issues


def validate_platform_support(root: Path) -> list[str]:
    return validate_platform_contracts(root) + validate_generated_outputs(root)


def _safe_generated_root(root: Path, relative: Path, *, operation: str) -> Path:
    if relative not in (*GENERATED_ROOTS, *RETIRED_GENERATED_ROOTS):
        raise ValueError(f"refusing to {operation} undeclared generated path: {relative}")

    resolved_root = root.resolve()
    target = resolved_root / relative
    if target == resolved_root or not target.is_relative_to(resolved_root):
        raise ValueError(
            f"refusing to {operation} generated path outside repository: {target}"
        )

    current = resolved_root
    for part in relative.parts:
        current /= part
        _assert_no_generated_path_indirection(current, operation=operation)
    return target


def write_generated_outputs(root: Path) -> int:
    for relative_root in (*RETIRED_GENERATED_ROOTS, *GENERATED_ROOTS):
        _safe_generated_root(root, relative_root, operation="replace")
    expected = expected_outputs(root)
    for relative_root in RETIRED_GENERATED_ROOTS:
        target = _safe_generated_root(root, relative_root, operation="replace")
        if target.exists():
            shutil.rmtree(target)
    for relative_root in GENERATED_ROOTS:
        target = _safe_generated_root(root, relative_root, operation="replace")
        if target.exists():
            shutil.rmtree(target)
        target.mkdir(parents=True)
    for relative, content in expected.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    return len(expected)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="replace generated adapter directories")
    mode.add_argument("--check", action="store_true", help="check generated output (the default)")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root",
    )
    args = parser.parse_args(argv)
    root = args.root.resolve()

    if args.write:
        try:
            count = write_generated_outputs(root)
        except (OSError, ValueError) as exc:
            print(f"Platform adapter generation failed: {exc}", file=sys.stderr)
            return 1
        print(f"Generated {count} platform adapter files.")
        return 0

    issues = validate_platform_support(root)
    if issues:
        print("Platform adapter validation failed:", file=sys.stderr)
        for issue in issues:
            print(f"- {issue}", file=sys.stderr)
        return 1
    print("Platform manifests and generated adapters are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
